Test GaussianMI with `normalized=false` and `true`
JuliaDynamics/CausalityTools.jl pull request #319
Opened 2023-08-23 21:21 UTC by RomeoV

Related to #318 but probably we can do a bit more before closing.

2023-08-24 20:09 UTC, kahaaga commented
Thanks for the contribution, @RomeoV! 

The tests will fail on this branch because the only file that has changed in this PR relative to  the `main` is the test file you modified. Therefore, the bug that you found for `GaussianMI` is still present in this `PR`. 

You can try merging your fork of the `main` branch onto this branch (the `test-gaussian-mi` branch). Then, if everything is correct after your changes in #318, the tests should hopefully pass here.

2023-08-24 20:27 UTC, kahaaga commented
Hey again, @RomeoV. After you merge your changes on `master` onto this branch, some tests will still fail. However, these are unrelated to the MI tests you added here (see #320). 

Take-away: When the MI tests you added pass, this PR is good. The other errors are due to some package requirements - I'll have a look at fixing those, and will release a new patch version of the package, once this PR is good to go.

2023-08-24 22:34 UTC, RomeoV commented
Test should pass now. I noticed that the default base of `MIShannon` is 2, but it's `e` "for the math". So I fixed that and had to increase the sample size a bit, and now it looks good!

Sidenote: I suppose `base=2` is common for computer science information theory, but this problem took me a while to find, as all the math on wikipedia assumes `base=\euler`. I don't know enough about the literature to judge which default choice has "less surprise" (😉) here though.

2023-08-25 08:07 UTC, kahaaga requested changes
The test suite for the MI still fails due to some syntax errors.

If you didn't already know, you can run the test suite locally in the REPL by activating the `CausalityTools` project folder, then typing `]` to enter package mode, and then typing `test`. Then the test suite will run, and you will get a summary of which test sets were successful and which were not. You'll see that in the current state of this PR, there's one mutual info testset that fails (it shows up in red):
<img width="537" alt="Screenshot 2023-08-25 at 10 06 26" src="https://github.com/JuliaDynamics/CausalityTools.jl/assets/5237566/1f77b071-e3b1-4969-a0d6-a043f8058549">

If you fix the syntax errors I highlighted, these errors should hopefully disappear!

2023-08-25 20:09 UTC, RomeoV commented
Sorry for that. I was a bit in a hurry, so I didn't want to run the whole test harness (although I should have) and just ran the inner code in a REPL. Thanks for picking up on it. Should be fixed now.

2023-08-26 08:52 UTC, kahaaga commented
> Sorry for that. I was a bit in a hurry, so I didn't want to run the whole test harness (although I should have) and just ran the inner code in a REPL. Thanks for picking up on it. Should be fixed now.

Perfect! Thank you so much for your effort. This looks good to go.

PS: in the future, if you contribute to this or other repos, it is helpful if you tick the "allow repo maintainers to make changes to the PR" button (I can't remember the exact wording, but there's an option like that when you open the PR).  That way, I can immediately fix minor things like the missing `begin` keywords myself, without us having to go back and forth over multiple days and time zones for minor details.

2023-08-26 08:52 UTC, merged